set number

set tabstop=4
set shiftwidth=4
set softtabstop=4

syntax on

let g:airline#extensions#tabline#enabled=1
let g:airline_theme='solarized'

nmap <C-Tab> :bn<CR>
nmap <S-Tab> :bp<CR>
nmap <C-x>   :bw<CR>

call plug#begin('~/vimfiles/bundle')

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-surround'

call plug#end()

