set number

set tabstop=4
set shiftwidth=4
set softtabstop=4

syntax on

let g:airline#extensions#tabline#enabled=1
let g:airline_theme='zenburn'

" Configure netrw
let g:netrw_banner = 0
let g:netrw_localrmdir="rm -r"
let g:netrw_browse_split = 2
let g:netrw_altv = 1
let g:netrw_liststyle = 3
let g:netrw_winsize = 20

nmap <C-Tab> :bn<CR>
nmap <S-Tab> :bp<CR>
nmap <C-x>   :bw<CR>

call plug#begin('~/.vim/bundle')

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-surround'

call plug#end()

